[project]
name = "dotfiles"
platforms = ["linux-64"]
channels = ["conda-forge"]

[dependencies]
python = "3.12.*"

[activation]
scripts = ["export_pythonpath.sh"]

[feature.main.dependencies]
prompt-toolkit = "~=3.0"
pydantic = "~=2.8"
pygments = "~=2.18"
semver = "*"
simple-parsing = "~=0.1.5"

[feature.main.pypi-dependencies]
pydantic-extra-types = "~=2.9"

[feature.main.tasks]
panoplie = { cmd = ["python", "-m", "panoplie"] }

[feature.development.dependencies]
ruff = "~=0.6.2"

[environments]
development = { features = ["main", "development"] }
main = { features = ["main"] }
