target-version = "py312"
required-version = ">=0.6.2"
line-length = 80

[lint]
fixable = ["ALL"]
select = []

[lint.isort]
known-first-party = ["panoplie"]
lines-between-types = 1
lines-after-imports = 2

[format]
